version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "firehydrant/open-source-maintainers"
  - package-ecosystem: "gomod"
    directory: "/_tools"
    schedule:
      interval: "daily"
    reviewers:
      - "firehydrant/open-source-maintainers"
