// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"database/sql"
)

type ExtEscalationPolicy struct {
	ID                string         `json:"id"`
	Name              string         `json:"name"`
	Description       string         `json:"description"`
	TeamID            sql.NullString `json:"team_id"`
	RepeatLimit       int64          `json:"repeat_limit"`
	RepeatInterval    sql.NullString `json:"repeat_interval"`
	HandoffTargetType string         `json:"handoff_target_type"`
	HandoffTargetID   string         `json:"handoff_target_id"`
	Annotations       string         `json:"annotations"`
	ToImport          int64          `json:"to_import"`
}

type ExtEscalationPolicyStep struct {
	ID                 string `json:"id"`
	EscalationPolicyID string `json:"escalation_policy_id"`
	Position           int64  `json:"position"`
	Timeout            string `json:"timeout"`
}

type ExtEscalationPolicyStepTarget struct {
	EscalationPolicyStepID string `json:"escalation_policy_step_id"`
	TargetType             string `json:"target_type"`
	TargetID               string `json:"target_id"`
}

type ExtMembership struct {
	UserID string `json:"user_id"`
	TeamID string `json:"team_id"`
}

type ExtRotation struct {
	ID            string `json:"id"`
	ScheduleID    string `json:"schedule_id"`
	Name          string `json:"name"`
	Description   string `json:"description"`
	Strategy      string `json:"strategy"`
	ShiftDuration string `json:"shift_duration"`
	StartTime     string `json:"start_time"`
	HandoffTime   string `json:"handoff_time"`
	HandoffDay    string `json:"handoff_day"`
	RotationOrder int64  `json:"rotation_order"`
}

type ExtRotationMember struct {
	RotationID  string `json:"rotation_id"`
	UserID      string `json:"user_id"`
	MemberOrder int64  `json:"member_order"`
}

type ExtRotationRestriction struct {
	RotationID       string `json:"rotation_id"`
	RestrictionIndex string `json:"restriction_index"`
	StartTime        string `json:"start_time"`
	StartDay         string `json:"start_day"`
	EndTime          string `json:"end_time"`
	EndDay           string `json:"end_day"`
}

type ExtSchedule struct {
	ID            string `json:"id"`
	Name          string `json:"name"`
	Description   string `json:"description"`
	Timezone      string `json:"timezone"`
	Strategy      string `json:"strategy"`
	ShiftDuration string `json:"shift_duration"`
	StartTime     string `json:"start_time"`
	HandoffTime   string `json:"handoff_time"`
	HandoffDay    string `json:"handoff_day"`
}

type ExtScheduleMember struct {
	ScheduleID  string `json:"schedule_id"`
	UserID      string `json:"user_id"`
	MemberOrder int64  `json:"member_order"`
}

type ExtScheduleRestriction struct {
	ScheduleID       string `json:"schedule_id"`
	RestrictionIndex string `json:"restriction_index"`
	StartTime        string `json:"start_time"`
	StartDay         string `json:"start_day"`
	EndTime          string `json:"end_time"`
	EndDay           string `json:"end_day"`
}

type ExtScheduleTeam struct {
	ScheduleID string `json:"schedule_id"`
	TeamID     string `json:"team_id"`
}

type ExtSchedulesV2 struct {
	ID               string `json:"id"`
	Name             string `json:"name"`
	Description      string `json:"description"`
	Timezone         string `json:"timezone"`
	TeamID           string `json:"team_id"`
	SourceSystem     string `json:"source_system"`
	SourceScheduleID string `json:"source_schedule_id"`
}

type ExtTeam struct {
	ID          string         `json:"id"`
	Name        string         `json:"name"`
	Slug        string         `json:"slug"`
	FhTeamID    sql.NullString `json:"fh_team_id"`
	IsGroup     int64          `json:"is_group"`
	ToImport    int64          `json:"to_import"`
	Annotations string         `json:"annotations"`
}

type ExtTeamGroup struct {
	GroupTeamID  string `json:"group_team_id"`
	MemberTeamID string `json:"member_team_id"`
}

type ExtUser struct {
	ID          string         `json:"id"`
	Name        string         `json:"name"`
	Email       string         `json:"email"`
	FhUserID    sql.NullString `json:"fh_user_id"`
	Annotations string         `json:"annotations"`
}

type FhTeam struct {
	ID   string `json:"id"`
	Name string `json:"name"`
	Slug string `json:"slug"`
}

type FhUser struct {
	ID    string `json:"id"`
	Name  string `json:"name"`
	Email string `json:"email"`
}

type LinkedTeam struct {
	ID          string         `json:"id"`
	Name        string         `json:"name"`
	Slug        string         `json:"slug"`
	FhTeamID    sql.NullString `json:"fh_team_id"`
	IsGroup     int64          `json:"is_group"`
	ToImport    int64          `json:"to_import"`
	Annotations string         `json:"annotations"`
	FhName      sql.NullString `json:"fh_name"`
	FhSlug      sql.NullString `json:"fh_slug"`
}

type LinkedUser struct {
	ID          string         `json:"id"`
	Name        string         `json:"name"`
	Email       string         `json:"email"`
	FhUserID    sql.NullString `json:"fh_user_id"`
	Annotations string         `json:"annotations"`
	FhName      sql.NullString `json:"fh_name"`
	FhEmail     sql.NullString `json:"fh_email"`
}
