// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package store

import (
	"database/sql"
)

type ExtMembership struct {
	UserID string `json:"user_id"`
	TeamID string `json:"team_id"`
}

type ExtSchedule struct {
	ID            string `json:"id"`
	Name          string `json:"name"`
	Description   string `json:"description"`
	Timezone      string `json:"timezone"`
	Strategy      string `json:"strategy"`
	ShiftDuration string `json:"shift_duration"`
	StartTime     string `json:"start_time"`
	HandoffTime   string `json:"handoff_time"`
	HandoffDay    string `json:"handoff_day"`
}

type ExtScheduleMember struct {
	ScheduleID string `json:"schedule_id"`
	UserID     string `json:"user_id"`
}

type ExtScheduleRestriction struct {
	ScheduleID       string `json:"schedule_id"`
	RestrictionIndex string `json:"restriction_index"`
	StartTime        string `json:"start_time"`
	StartDay         string `json:"start_day"`
	EndTime          string `json:"end_time"`
	EndDay           string `json:"end_day"`
}

type ExtScheduleTeam struct {
	ScheduleID string `json:"schedule_id"`
	TeamID     string `json:"team_id"`
}

type ExtTeam struct {
	ID       string         `json:"id"`
	Name     string         `json:"name"`
	Slug     string         `json:"slug"`
	FhTeamID sql.NullString `json:"fh_team_id"`
}

type ExtUser struct {
	ID       string         `json:"id"`
	Name     string         `json:"name"`
	Email    string         `json:"email"`
	FhUserID sql.NullString `json:"fh_user_id"`
}

type FhTeam struct {
	ID   string `json:"id"`
	Name string `json:"name"`
	Slug string `json:"slug"`
}

type FhUser struct {
	ID    string `json:"id"`
	Name  string `json:"name"`
	Email string `json:"email"`
}
