// Code generated by "stringer -type=ScheduleStrategy"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Weekly-0]
	_ = x[Daily-1]
}

const _ScheduleStrategy_name = "WeeklyDaily"

var _ScheduleStrategy_index = [...]uint8{0, 6, 11}

func (i ScheduleStrategy) String() string {
	if i < 0 || i >= ScheduleStrategy(len(_ScheduleStrategy_index)-1) {
		return "ScheduleStrategy(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ScheduleStrategy_name[_ScheduleStrategy_index[i]:_ScheduleStrategy_index[i+1]]
}
